name: Generate ASCII Artwork Using Shell script

on: 
  push

jobs:
    ascii_job_shell: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List File
          run: ls -ltra

        - name: Executing Shell script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh
