name: Multi-line Command

on: push

jobs:
    second_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: List and Read file
          run: |
            echo "My first Github Action Job"
            ls -ltra
            cat README.md
        
      